config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
   }

  devise_scope :user do
    get "sign_in", to: "users/sessions#new"
    get "sign_out", to: "users/sessions#destroy" 
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'posts#index'
  resources :posts do
    resources :comments, only: :create
    collection do
      get 'search'
    end
  end
  resources :users, only: :show
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :content, presence: true
  validates :title, presence: true

  belongs_to :user
  has_many :comments

  def self.search(search)
    return Post.all unless search
    Post.where('title LIKE(?)', "%#{search}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  def self.guest
    find_or_create_by(email: "test@com") do |user|
      user.password = Rails.application.secrets.test_account_pass
    end
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/posts/ #{comment.post.id}"
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_tweet, only: [:edit, :show]
  before_action :move_to_index, except: [:index, :show, :search]

  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
  end

  def edit
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
  end

  def show
    @comment = Comment.new
    @comments = @post.comments.includes(:user).order("created_at DESC")
  end

  def search
    @posts = Post.search(params[:keyword])
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image).merge(user_id: current_user.id)
  end

  def set_tweet
    @post = Post.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  def new_guest
    user = User.guest
    sign_in user
    redirect_to root_path, notice: "Thank you for your testing!"
  end

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @posts = user.posts.order("created_at DESC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_notifications.html.haml
.Notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Comigest
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %header.header
      .header__bar.row
        %h1.grid-6
          %a{:href => "/"} Comigest
        - if user_signed_in?
          .user_nav.grid-6
            %span
              = current_user.nickname
              %ul.user__info
                %li
                  = link_to "マイページ", "/users/#{current_user.id}"
                  = link_to "ログアウト", destroy_user_session_path, method: :delete
            = link_to "投稿する", new_post_path, class: "post"
        - else
          .grid-6
            = link_to "ログイン", new_user_session_path, class: "post"
            = link_to "新規登録", new_user_registration_path, class: "post"
    = render 'layouts/notifications'
    = yield
    %footer
      %p
        Copyright Comigest 2020.

app/views/posts/_form.html.haml
= form.text_field :title, placeholder: "Title"
= form.text_field :image, placeholder: "Image URL"
= form.text_area :content, placeholder: "Content", rows: "10"
= form.submit "SEND"

app/views/posts/_post.html.haml
.content_post{:style => "background-image: url(#{post.image});"}
  .more
    %span= image_tag 'arrow_top.png'
    %ul.more_list
      %li
        = link_to '詳細', post_path(post.id), method: :get
      - if user_signed_in? && current_user.id == post.user_id
        %li
          = link_to '編集', edit_post_path(post.id), method: :get
        %li
          = link_to '削除', post_path(post.id), method: :delete
  %span.name
    %a{:href => "/users/#{post.user.id}"}
      /%span 投稿者
      - post.user.nickname

app/views/posts/create.html.haml
.contents.row
  .success
    %h3 投稿が完了しました。
    %a.btn{:href => "/posts"} 投稿一覧へ戻る

app/views/posts/destroy.html.haml
.contents.row
  .success
    %h3 削除が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/posts/edit.html.haml
.contents.row
  .container
    = form_with(model: @post, local: true) do |form|
      %h3 編集する
      = form.text_field :title, placeholder: "Title"
      = form.text_field :image, placeholder: "Image Url"
      = form.text_area :content, placeholder: "Content", rows: "10"
      = form.submit "SEND"

app/views/posts/index.html.haml
%h1 Hello World!

app/views/posts/new.html.haml
.contents.row
  .container
    = form_with(model: @post, local: true) do |form|
      %h3 投稿する
      = render partial: "form", locals: { form: form }

app/views/posts/search.html.haml
= form_with(url: search_posts_path, local: true, method: :get, class: "search-form") do |form|
  = form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input"
  = form.submit "検索", class: "search-btn"
.contents.row
  - @posts.each do |post|
    = render partial: "post", locals: { post: post }

app/views/posts/show.html.haml
.contents.row
  .content_area
    .content_post{:style => "background-image: url(#{@post.image});"}
      - if user_signed_in? && current_user.id == @post.user_id
        .more
          %span= image_tag 'arrow_top.png'
          %ul.more_list
            %li
              = link_to '編集', edit_post_path(@post.id), method: :get
            %li
              = link_to '削除', post_path(@post.id), method: :delete
      %span.name
        %a{:href => "/users/#{@post.user.id}"}
          %span 投稿者
          = @post.user.nickname
    .content_digest
      .title
        %span= @post.title
      .content
        %details
          %summary
            要約・感想
          = @post.content
  .container
    - if current_user
      = form_with(model: [@post, @comment], local: true) do |form|
        = form.text_area :text, placeholder: "コメントする", rows: "2"
        = form.submit "SEND"
    - else
      %strong
        %p ※※※ コメントの投稿には新規登録/ログインが必要です ※※※
    .comments
      %h4 ＜コメント一覧＞
      - if @comments
        - @comments.each do |comment|
          %p
            %strong
              = link_to comment.user.nickname, "/users/#{comment.user_id}"
              ：
            = comment.text

app/views/posts/update.html.haml
.contents.row
  .success
    %h3 更新が完了しました。
    %a.btn{:href => "/"} 投稿一覧へ戻る

app/views/users/show.html.haml
.contents_myPage.row
  %p
    = @nickname
    さんの投稿一覧
  .contents.row.flex
    - @posts.each do |post|
      = render partial: "posts/post", locals: { post: post }